### ISSUE TITLE
PIP Install Not Working in VS Code

### ISSUE THREAD

**Issue by raeldor** [synchronizing/bluelink#1]
ERROR: Could not find a version that satisfies the requirement bluelink (from versions: none)
ERROR: No matching distribution found for bluelink

**Comment by synchronizing** [comment]
Might be an issue specific to your computer, not the project. The project is on PyPi here: 

https://pypi.org/project/bluelink/

**Comment by raeldor** [comment]
Thank you for your prompt reply.  I got rid of Anaconda completely in favor of regular venv in Windows and now it's working.  Apologies for the false alarm.
