### ISSUE TITLE
Unable to send your request because a previous request is pending. Please wait and try again later.

### ISSUE THREAD

**Issue by raeldor** [synchronizing/bluelink#2]
I get this error every time, even though I'm able to log in using the app successfully.  Is there anything region specific to this API, or should it work in all regions worldwide?

```python
Exception has occurred: RequestFailed
Unable to send your request because a previous request is pending. Please wait and try again later.
  File "D:\My Documents\Repos\bluelink-test\bluelink-test.py", line 7, in <module>
    bl.login()
```

**Comment by raeldor** [comment]
I think my region might be very different.  Using Charles I'm getting something similar to this for web calls...

<img width="319" alt="image" src="https://user-images.githubusercontent.com/1768444/186893792-a9580db7-63bd-43db-8304-1942c9239214.png">

**Comment by synchronizing** [comment]
Looks like it is indeed a different region. This project is using the US API endpoint; `https://owners.hyundaiusa.com`.

**Comment by raeldor** [comment]
It looks like it's using a completely different API.  I can't see reference to these url paths in your code.

**Comment by raeldor** [comment]
May I ask how you discovered the JSON payload formats?  I would like to make a Japanese version, but Charles did not seem to return any of the data or response information.  Thanks.

**Comment by raeldor** [comment]
I tried to send a request using Postman to the Japan API, but I get 'Error: self signed certificate in certificate chain'.  If I turn off SSL certificate verification I get the response...
{
    "errId": "34e8218e-08f9-47d6-adc6-ddce0025b623",
    "errCode": "4010",
    "errMsg": "Require authentication"
}

**Comment by raeldor** [comment]
I have a feeling the API here might be using client side certificates.

**Comment by RapidCompiler** [comment]
I am facing the same error as well. My bluelink account is based out of India. Will I not be able to use this package and API then?

**Comment by synchronizing** [comment]
I don't have access to the Japan or India API. My best guess is that Hyundai - for whatever reason - has different APIs for different countries. I'm willing to work alongside you guys to add support for these regions if that's something you guys are interested in.

Closing this issue for now, but feel free to keep discussion alive.

**Comment by raeldor** [comment]
I've made some progress.  It appears to be a completely different API.  The first time you log in, you have to do so using form based authentication.  Then you can pick up your code,  which can then be used to get your tokens.  It's kind of hard going, since even the Korean developer portal documentation appears to be way out of date.

**Comment by synchronizing** [comment]
The US API is similar in regards to form-based authentication. The flow is as follow:

1. Retrieve [CSFR token](https://portswigger.net/web-security/csrf/tokens) for form `POST`. They wrongfully (or purposely?) mislabeled it as a `jwt_token`. 

https://github.com/synchronizing/bluelink/blob/1d8a8901b8ce39e1aa610e0e0e973df9553b68ea/bluelink/bluelink.py#L275-L285

2. Simulate form `POST` request with the CSFR token to retrieve a legit JWT token.

https://github.com/synchronizing/bluelink/blob/1d8a8901b8ce39e1aa610e0e0e973df9553b68ea/bluelink/bluelink.py#L287-L299

3. Retrieve the [JWT token](https://en.wikipedia.org/wiki/JSON_Web_Token) from the login for follow-up requests.

https://github.com/synchronizing/bluelink/blob/1d8a8901b8ce39e1aa610e0e0e973df9553b68ea/bluelink/bluelink.py#L301-L305

Let me know if I can be of help reverse engineering the API. I've noticed that there is differences between the web API, and the mobile API. You can use either Chrome's Network tab, or you use something like [`mitmproxy`](https://mitmproxy.org/) to capture the requests coming out of the mobile app.
